export const meta = {
  name: 'minioutbreak-track',
  description: 'One MiniOutbreak track (chosen by args.track): build in its worktree, adversarial review against the original Mini DayZ and the ask, fix',
  phases: [
    { title: 'Build', detail: 'the track, step by step' },
    { title: 'Review', detail: 'one adversarial reviewer, original side by side' },
    { title: 'Fix', detail: 'fix what the review found, only when it found something' },
  ],
}

const SP = '/tmp/claude-0/-home-user-MiniDAYZcustom/0ff86e18-6019-5d27-9ca6-6fb5467d12e7/scratchpad'
const BASE = 'b180a9d'

const COMMON = (t) => `
You are working on MiniOutbreak, a LÖVE 11.5 remake of the web game Mini DayZ (web build: love.js 11.4, WebGL1, PUC Lua 5.1, published from main to exyoff.github.io/MiniOutbreak). The user plays the published web build ON A PHONE held sideways, and on PC.
YOUR WORKTREE: /home/user/wt/${t} on branch work/${t}, branched from ${BASE} (Stage 26, published). Work ONLY there. Never touch /home/user/minioutbreak or any other worktree. Never push. Never switch branches.

THE ORIGINAL GAME IS NOW AT HAND -- the user's standing instruction (2026-10-03): "compare against official minidayz, use screenshots and source code to compare. Do not stop working until it is identical except for the changes i had asked for specifically."
- /home/user/MiniDAYZcustom/MiniDayZ+1.0 is the official browser build (Bohemia's Construct 2 export, v1.4-era, only its page title changed): data.js (the whole project: object types, animations with frame rects in the sheets, event sheets = the game's logic, layouts, audio, globals), images/*.png (the COMPLETE sprite sheets -- the remake's Assets/Sprites rip lacks ~80 objects, all present here), media/ (sounds), l_eng_*.xml (texts). MiniDayZ+1.2 and MiniDayZ+Reloaded are fan mods: never the reference.
- OriginalData/ in your worktree links to /home/user/OriginalData: C2SourceData.js (= that data.js, BOM stripped), images/ and game/ (the build). tools/c2data.py and the tools/extract_*.py read it (docs/original_data.md says how, and what surprised us). Never commit anything from it; generated outputs the build already commits (game/data/generated, tools/generated) may be regenerated by the tools.
- A readable dump of the event sheets may appear at ${SP}/orig/events/ (another agent is writing it; use it if there, else read data.js with python: json.load, project[6] are the event sheets, project[3] object types whose names come from their frames' image paths -- c2data.load_sprites).
- RUN THE ORIGINAL: \`${SP}/orig/serve.sh\` (serves it on 127.0.0.1:8731 if not already), then \`node ${SP}/orig/orig.cjs --out DIR --res 1280x720 [--touch] --steps "wait:20000;shot:menu;click:640,353;wait:4000;shot:difficulty;..."\` (read the header of orig.cjs for every step: wait, shot, click, tap, down/up/move, key, hold/release, js -- \`js:\` evaluates in the page; cr_getC2Runtime() is the C2 runtime, so you can read and set its globals and instances, e.g. teleport, give items, set the time). It boots to its menu in ~20 s; "New game" opens Novice/Regular/Veteran/Legend. LOOK at its screenshots beside the remake's.
- The user's own asks -- every deliberate difference from the original, which must be KEPT -- are compiled in ${SP}/user_asks.md (read it). Where the remake differs from the original and no ask covers it, the original wins.

Read first: docs/conventions.md, docs/architecture.md, docs/original_data.md, Progress.md's "Ground rules" and "Where this stands", and the Progress stages your text names. Hard rules: Lua 5.1 only; hot-reload conventions (require whole modules, read cfg at call time, no GPU objects at module scope, src/core never requires game/ui, src/game/systems never requires src/ui); worldgen draws only from its own seeded stream; no new per-frame garbage in hot paths; only combat.lua's one door may hurt the player (a lint); a scenario asserts state, not strings.

RUNNING THE REMAKE. Always \`source ${SP}/env/${t}/env.sh\` first (a private LÖVE save dir, Xvfb).
- A capture: \`python3 ${SP}/env/${t}/cap.py NAME FRAMES BEAT RES SCRIPTFILE [--touch off] [--world 7]\` -- SCRIPTFILE holds a Python expression evaluating to a list of script steps, with everything from tools/scenarios/common.py in scope (START, GOD, KILL, lua(...) ...) plus PHONE_START. It writes ${SP}/env/${t}/caps/NAME.png (the LAST frame) and prints the log's "= " lines. RES 1280x720 and 844x390. LOOK at the PNGs with the Read tool. Console \`lua\` lines under 160 characters, no ';', printed values without ':'. \`--world <seed>\` starts a generated world.
- Scenarios: tools/scenarios/<subject>.py (CHANGES rows in __init__.py for new files). Run by name: \`python3 tools/verify.py "<part of the name>"\`; the lint subject whole: \`python3 tools/verify.py --subject lint\`.
TESTING RULE FROM THE USER: do NOT run the full suite, \`--changed\` or whole subjects (lint excepted). Run only the scenarios you wrote or changed, plus the lints, plus the few existing ones your change reaches. Every scenario begins with common.py's START (two presses); a capture's START builds the test map.
- Art: the rip (Assets/Sprites) lacks objects the original has; cut what you need from OriginalData/images with the frame rects in data.js (the way tools/build_atlas.py and build_furniture.py already treat the rip), committing the cut PNGs under Assets/Sprites/<object>/ in the rip's own layout (default_N.png per animation frame, names as the original's), so the normal build packs them. Then \`python3 tools/build.py --only atlas\` (and --only icons) -- every OTHER committed generated file must stay byte-identical.

COMMITS. Commit early and often on work/${t}. Every commit message ends with exactly:
Co-Authored-By: Claude Opus 5.5 <noreply@anthropic.com>
Claude-Session: https://claude.ai/code/session_01VdQG643pr7XgRazEVt5gSB
No model names anywhere else. Update README.md / docs where they describe what you changed. Do NOT edit Progress.md -- return your progress entry.

Be efficient; match the surrounding comment density and the Progress.md voice. Choices that are the user's: make a sensible one, list it in "choices" with the one change that reverses it.
`

const BUILD_SCHEMA = {
  type: 'object',
  properties: {
    summary: { type: 'string' },
    commits: { type: 'array', items: { type: 'string' } },
    files: { type: 'array', items: { type: 'string' } },
    shared_code_touched: { type: 'array', items: { type: 'string' } },
    generated_files_changed: { type: 'array', items: { type: 'string' } },
    scenarios_added: { type: 'array', items: { type: 'string' } },
    scenarios_changed: { type: 'array', items: { type: 'string' } },
    scenarios_run: { type: 'string' },
    captures: { type: 'array', items: { type: 'string' } },
    measurements: { type: 'array', items: { type: 'string' } },
    original_compared: { type: 'array', items: { type: 'string' }, description: 'what of the original was looked at (screens, events, data) and what matched or deliberately differs' },
    choices: { type: 'array', items: { type: 'string' } },
    art_wanted: { type: 'array', items: { type: 'string' } },
    found: { type: 'array', items: { type: 'string' } },
    progress_entry: { type: 'string', description: 'markdown in the Stage 26 style: "### N.M Title", a short paragraph, "- [x] N.M.K **Lead.** prose" items quoting the user, "*Verified by capture: ...*" lines; "- [ ]" for found/not done' },
    dated_notes: { type: 'string', description: 'notes for earlier items this overturns, "- **N.N.N** (2026-10-03): ..." -- or "none"' },
  },
  required: ['summary', 'commits', 'files', 'shared_code_touched', 'generated_files_changed', 'scenarios_added', 'scenarios_changed', 'scenarios_run', 'captures', 'measurements', 'original_compared', 'choices', 'art_wanted', 'found', 'progress_entry', 'dated_notes'],
}
const REVIEW_SCHEMA = {
  type: 'object',
  properties: {
    verdict: { type: 'string' },
    findings: { type: 'array', items: { type: 'object', properties: {
      severity: { type: 'string', enum: ['blocker', 'major', 'minor', 'nit'] },
      title: { type: 'string' }, where: { type: 'string' }, detail: { type: 'string' },
    }, required: ['severity', 'title', 'where', 'detail'] } },
  },
  required: ['verdict', 'findings'],
}
const FIX_SCHEMA = {
  type: 'object',
  properties: {
    summary: { type: 'string' },
    fixed: { type: 'array', items: { type: 'string' } },
    not_fixed: { type: 'array', items: { type: 'string' } },
    commits: { type: 'array', items: { type: 'string' } },
    scenarios_added: { type: 'array', items: { type: 'string' } },
    scenarios_changed: { type: 'array', items: { type: 'string' } },
    scenarios_run: { type: 'string' },
    captures: { type: 'array', items: { type: 'string' } },
    progress_entry: { type: 'string', description: 'the FULL updated entry for the track (every item of it)' },
    dated_notes: { type: 'string' },
  },
  required: ['summary', 'fixed', 'not_fixed', 'commits', 'scenarios_added', 'scenarios_changed', 'scenarios_run', 'captures', 'progress_entry', 'dated_notes'],
}

const RESUME = (t) => `THIS TRACK WAS STARTED BEFORE AND STOPPED PART-WAY (a usage limit ended the agent, not a decision). Read \`git -C /home/user/wt/${t} log --oneline ${BASE}..HEAD\`, \`git status\` and \`git diff\` FIRST: keep what is sound, finish what is half-done, commit it.`

const TRACKS = {
  rooms: {
    items: '27.1',
    steps: [
      `${RESUME('rooms')}
Item 27.1: "Some building interiors are still missing". Assets/Sprites has a <name>_int folder for 36 buildings; data/buildings.lua makes 15 enterable. These 21 have interior art and no room: b_village_brown, b_village_green, b_village_red2, b_village_yard, b_village_yellow, b_small_shed, b_garage_green, b_hunter_shelter, b_gas_station_fueling, b_city_house_3, b_city_house_4, b_piano_house, b_hostel, b_gunshop, b_supermarket, b_school, b_police_station, b_church, b_castle, b_dot, b_car_bus. (b_deer_stand, b_garage_brown, b_shadows: check the ORIGINAL's images for an _int sheet before calling them facades.)
TAKE EACH FROM THE ORIGINAL'S OWN DATA, not by eye: docs/original_data.md says how the original builds every building (the _int plate spawned at the placement's origin, the facade at the plate's hotspot, the door at the facade's Imagepoint 3 (4 or 6 for some), the plate's collision polygon = the room's walls with the doorway open, obst_base / big_obstacle_base frames at the plate's image points, furniture spawned at image points) -- read those events and frames in data.js for each of the 21 and derive: the anchor (data/sprite_anchors.lua), the door point and style, the wall rects (data/colliders.lua, from the plate's polygon), the furniture and where it stands (what the original spawns there and its container type), the floor line. The 15 existing rooms were built the same way (23.1-23.3): follow their pattern and the rooms/door/furniture lints. Loot: what the original's containers in each building roll (data.js's loot logic), mapped onto data/loot_tables.lua; new tables only where the original has a distinct one.
LOOK at the original: in a run, teleport the player (js: through cr_getC2Runtime()) to one of each building and screenshot it from outside and inside; compare with the remake's capture at the same size. Facade, cutaway, door and furniture must match.
Scenarios (world subject): one table-driven scenario that for EVERY enterable building (old and new) spawns it on the test map from the console (interior.make_enterable), opens its door, walks the player in through the doorway and reads: filed in the room, sheltered, the door lint's three points agreeing, every container reachable from inside and none from the street. Captures of each new room from the street and from inside at 1280x720 and 844x390, LOOKED at.
Commit after every few buildings. This step: all 21, the small ones first.`,
    ],
    review_focus: `The ask: "Some building interiors are still missing" -- now against the original side by side. For every building with interior art (the remake's 36 and any the original has beyond them): enterable; the cutaway exactly where the original puts it (screenshot the original in a run beside the remake's capture, magnified); the door where the original's facade has it, opening and shutting; the walls solid with only the doorway open; the furniture the original has, where it has it, searchable from inside only, rolling what the original's would; the far wall sorting over whoever stands north of it; shelter and the dark outside work in it; the lints; generated worlds still build (several seeds, the perf scenarios by name); the test map unchanged; generated files byte-identical except what the change regenerates.`,
  },
  map: {
    items: '27.2, 27.3',
    steps: [
      `${RESUME('map')}
THIS IS THE THIRD RUN OF THIS STEP: two before you were cut off by a usage limit with 25-30 files uncommitted (they are still in the worktree -- read them, keep what is sound). COMMIT EVERY SOUND PIECE AS SOON AS IT WORKS, at least every 30-40 minutes.
Item 27.2: a much bigger world that still runs on a phone. The user's words: "Increase the height" (= the generated world's height; answered when asked), "make the biomes wider, like 100 across, just for testing" (= 100 ground tiles, 6000 px, per season). Read Progress Stage 21, 25.2, 26.3, 26.4.
(a) THE SIZE. data/lots.lua is an 8x8 grid of 1200 px lots, one column the coast; data/ground.lua's seasons are five bands at fractions of the width. Make each season a set number of CELLS wide (seasons.cells = 100, 6000 px; the ragged wander stays) and derive the land's width: 5 x 6000 = 30000 px = 25 lots, plus the coast's lot -> 26 across; the rows their own number, 16 (19200 px). bands.cold ramps over the new edges as before; the beach, the spawn and its home unchanged; generate.VERSION up (a Stage 26 save refused, as 26.3.9 refused Stage 25's -- say so).
(b) MEASURE and keep 25.2's budgets: entity and body counts, generation time natively (JIT off) and in the web build throttled 4x, frame time natively and in the web build at 4x (tools/web_perf.cjs) in a town, on a road, in a base, the autosave's size and time -- against the 8x8 world. Where world scale shows in a per-frame loop, fix the loop; if a world built at once cannot meet the budgets or makes START or the autosave hitch on a phone, BUILD LOTS AS THE PLAYER REACHES THEM (the map table generated whole at START, a lot's entities spawned the first time the player comes within two lots of it and kept, map_index unchanged so the save and containers' state are unchanged, a never-spawned lot has nothing to save). Show the numbers.
(c) THE MINIMAP for a world this size reads at 844x390, and its static batch is not rebuilt per frame.
(d) SCENARIOS: update every generated-world scenario that reads seed 7's positions (grep worldgen, --world, "world":, seed, coast, seasons, cold, fill, roads, places, perf, minimap, doors) so each asks the same question of the bigger world; add the world's size from the cells and rows, each band 100 cells wide, the cold ramp, the budgets (and, if lazy, a far lot empty until approached then whole, a save with a lot unspawned loading right). Captures (--world 7, 1280x720 and 844x390).
Commit after (a), (b) and (d).`,
      `THIS STEP WAS STARTED BEFORE and cut off by a usage limit: 27.3(a) and (b) are committed (0f62538, bb81abc) and some files are uncommitted -- read git log, git status and git diff first, keep what is sound, finish (c), and COMMIT EACH PIECE AS SOON AS IT WORKS.
Item 27.3: more interest points, with roads connecting every one to every other. The user's words: "More interest points with roads connecting them" and, asked what "make the map grid uniform" meant: "Roads connect every interest point to each other". Your 27.2 is committed: read git log ${BASE}..HEAD first.
FIRST READ THE ORIGINAL'S WORLD: data.js's layouts (project[5]) and the events that build its map -- which places (towns, cities, bases, farms, camps, castle, church, bunker, helipad, checkpoints, crash sites...) it has, how many, which buildings and props each holds, how its roads run -- and screenshot its map screen in a run (the original has one). Take the kinds, their contents and proportions from it.
(a) MORE INTEREST POINTS: scale the counts to the bigger land (say them), add the original's kinds the remake lacks (from its data; their art is in OriginalData/images if the rip lacks it -- cut it into Assets/Sprites as the common notes say), each with loot brackets and zombie points (fill's brackets lint) and its minimap symbol; spread over every season, none on the coast; the beach's farmhouse kept (26.3.11).
(b) ROADS CONNECT EVERY INTEREST POINT TO EVERY OTHER: place the points first, then build the network to join them -- one connected graph (a minimum spanning tree over the places' road points plus loop links between near places), roads on the lot seams every prefab keeps clear (21.3), the coast road and the spawn's home in the graph, each road piece from its band's sheet with the season lines pinned (26.4.9). Measure the road-draw budget (25.2) on the bigger world.
(c) SCENARIOS (world subject): every place reachable from every other by road over twenty seeds (walk the graph in the map table); counts per kind in their brackets; every kind placed over a few seeds; nothing on the coast; the spawn's road in the graph; roads only on seams; the perf scenarios by name; the lints. Captures (--world 7 and two other seeds) of the minimap/network and a few new places, beside the original's.
Commit after (a), (b) and (c).`,
    ],
    review_focus: `The asks: five seasons of 100 tiles each and a taller world; more interest points; roads connecting every interest point to every other -- and, where the user asked nothing, the original's kinds of places and their contents. Re-measure every claimed number (entities, generation native and web at 4x, frame time at 4x in a town and a base, the autosave's size and time, draw calls) against the 8x8 world; the coast, spawn and home over 50 seeds; the cold ramp; if lots are built lazily -- never popping in on screen, a zombie chasing across an unspawned lot, a save with unspawned lots loaded, a container spawned after a load stocked once and its searched state kept; the road graph connected over many seeds (your own walk); no road across a prefab or on the sand; each new kind's prefab whole and like the original's; loot brackets; the minimap at 844x390; the test map pixel-identical; no per-frame garbage; the lints.`,
  },
  mapscreen: {
    items: '27.4',
    steps: [
      `${RESUME('mapscreen')} Its commits so far: 27.4(a) a MAP button, the M key, and a map screen that opens and shuts over a held run; 27.4(b) the whole world on the map screen from a static batch built once a world. Left: (c) the scenarios, docs, lints.
The user's words: "also make the map into an openable menu, clicking a button opens and closed the map", and since: "As for the map button, use the notepad looking button."
(a) THE BUTTON'S FACE: the original has a map button that looks like a notepad (find it in OriginalData/images and data.js -- e.g. a gui_btn_map / notes / journal sheet; screenshot the original's HUD in a run to see it and where it sits). Use that art (cut into Assets/Sprites as the common notes say), at the original's size, replacing the face laid together from a plate and minimap symbols.
(b) THE SCREEN AGAINST THE ORIGINAL: open the original's map in a run (its button) and screenshot it at 1280x720 and with --touch at 844x390: its frame, scale, what it shows (explored areas? marks? the player's arrow? legend?), how it opens and closes, whether the world pauses behind it. Make the remake's map screen match it, keeping only what the user asked (a button that opens and closes it; the remake's generated world as what it shows). Where the original shows something the remake's world lacks, say so.
(c) SCENARIOS (hud subject, a "map:" group): the button toggles the screen open and shut and M does; the world holds still while it is up if the original's does (else not); Escape and the phone's back key close it; the bag button while it is up; the screen inside the dead zone at 844x390 with F12's overlap none; the static picture built once (a counter) and the draw calls under a budget; never on the menu or the death screen. Run the existing Escape-chain and touch-overlap scenarios by name. Captures beside the original's.
Commit after (a), (b) and (c).`,
    ],
    review_focus: `The asks: a button opens and closes the map; the button is the original's notepad-looking one; and otherwise the map screen as the original's. Break it: every way in and out (the button, M, BACK, Escape, the phone's back key, the bag while it is up, a second tap, while the settings window or the inventory is up, during a crouched use, in build mode, while dead, on the menu); the world paused or not as the original; the picture right in a generated world and the test map (magnify; the player's mark where he is); the button's art the original's at its size and place (screenshot both); not rebuilt per frame; draw calls; the dead zone at 844x390; F12 at three sizes; the lints.`,
  },
  fauna: {
    items: '28.1, 28.2',
    steps: [
      `Item 28.1, step 1 of 2: what a zombie's attack sounds like, and the outside of buildings.
The user's words (2026-10-03): "the zombie attacking sound should just sound like a hit sound. The current sound is for wolfs." and "And some bugs: Building exteriors get hidden when rotating device, i think. Either way, the current way it works is incorrect. Make it hidden only when the player is inside".
(a) THE ZOMBIE'S ATTACK SOUND: data/sounds.lua plays attack = { zed_tank_1..3, wolf_attack } (and the rest) when a zombie attacks. Find in the ORIGINAL's events what plays when a zombie swings at and hits the player (data.js's event sheets; media/ names) and use exactly that -- a hit sound -- for the zombie; the wolf_* sounds are for wolves (28.2). Check every zombie archetype (the tank's own scream stays if the original's tank screams).
(b) EXTERIORS HIDDEN ONLY WHEN THE PLAYER IS INSIDE: 26.1 made every room's cutaway show from the street (cfg.interiors.always_cutaway = true). The user now says that is wrong: the facade shows from outside, and is hidden only while the player is inside -- which is the original's behaviour (check it in the original: walk up to and into a building, screenshot). Turn the switch off and make that the only behaviour (keep the dark outside from inside, the drops drawn over the floor, furniture reached only from in the room -- 26.1's other parts the user did not object to); retire the switch if nothing else needs it, and update the scenarios 26.1 wrote for always-on cutaways. Then "when rotating device": reproduce on the remake -- a resize/turn of the screen at 1280x720 -> 844x390 -> 390x844 -> 844x390 with the player outside and inside a building (the phone subject's turn scenarios show how) -- and find whether a turn hides a facade, puts the player "inside", or flips the art; fix the cause. Also check the original's fade of a facade the player stands behind: if the original fades it, keep the fade; if not, match the original.
Scenarios: the facade drawn from the street and the cutaway only while inside, for the test map's buildings; a turn of the screen leaves both as they were, outside and inside; the zombie's attack plays the original's hit sound and no wolf sound (audio.played or the sound log, as the audio scenarios read it). Run the existing interiors/doors/render scenarios that 26.1 changed, by name.
Commit after (a) and (b).`,
      `${RESUME('fauna')} (Its 28.1 is done and committed; of 28.2 the animals' bodies are cut and committed -- e9cf764 -- and the rest is yours.)
Item 28.2, step 2 of 2: animals. The user's words: "add animals, wolf chasing player or deer makes the current zombie attack noise." (The current zombie attack sound -- the wolf's -- goes to the animals.) Your 28.1 is committed: read git log ${BASE}..HEAD first.
THE ORIGINAL HAS THEM: read its object types, animations and events for wolves, deer, rabbits (and any other animal) -- their sprites (OriginalData/images: wolf*, deer*, rabbit* sheets), stats (health, speed, damage, sight and hearing ranges), AI (a wolf spots the player -- wolf_spot -- and chases and bites -- wolf_attack; a deer flees -- deerrun; a rabbit?), where and how many spawn (biomes, time of day, packs), what a dead one leaves (deer_dead / deer_dead_done, deer_skin, wolf_skin, rabbit_skin, raw_steak, raw_rabbit_steak -- and whether a knife skins/butchers it and a fire cooks the steak: cooked_rabbit_steak), and the hunting bits (the deer stand). Build them the way the original has them, as a new kind beside zombies (src/game/animal.lua or by extending zombie.lua's archetypes -- your call, said), with their sprites cut from the original's sheets into Assets/Sprites, their sounds from the rip (wolf_attack*, wolf_spot*, deerrun), physics bodies, the AI system (sleeping far ones as 25.2 sleeps zombies), population/spawn in generated worlds and the test map (a few near the test map's woods), damage to the player only through combat.lua's one door (the lint), shot and hit like a zombie, the loot/items they leave (items already in data/items.lua where they exist; add the original's otherwise, with their icons), and saving with the run. The original's numbers, not invented ones -- say each one's source.
LOOK at the original: spawn a wolf and a deer near the player (js: through cr_getC2Runtime() -- create the object or teleport to one) and screenshot them; capture the remake's beside them.
Scenarios (combat/world subjects): a wolf spots the player at its range, plays its spot sound, chases and bites (damage through the door, its attack sound); a deer flees from the player at its range; each dies to rounds and swings and leaves its carcass and items; animals spawn in a generated world in their numbers and not on the coast; far animals sleep; a save with animals loads them; perf (the soak/perf scenarios by name). Captures at 1280x720 and 844x390 beside the original's.
Commit after the sprites, after the AI and after the scenarios.`,
    ],
    review_focus: `The asks: the zombie's attack is a hit sound, the wolf's sound goes to wolves; animals -- wolves that chase and bite, deer -- as the original has them; exteriors hidden only while the player is inside, and nothing a screen turn does to them. Break it: the sounds each archetype plays (and the original's, from its events); the facade outside / cutaway inside on the test map and in a generated world, through every turn and resize sequence, at the doorway, on load inside; 26.1's dark outside and drops still right; the animals against the original side by side (sprites, size, speed, sight, damage, AI, sounds, drops, where they spawn), a wolf chasing through a doorway and round a wall, a deer cornered, animals vs zombies, animals asleep far off, a save/load with animals, the lint on player damage, perf (entities, frame time), no per-frame garbage, the test map's baseline scenarios that a wolf near the woods could disturb (run a sample by name).`,
  },
}

const key = (args && args.track) || 'rooms'
const T = { key, ...TRACKS[key] }

function buildPrompt(t, i) {
  return `${COMMON(t.key)}\nYOUR TRACK: ${t.key} (Progress items ${t.items}).\n\n${t.steps[i]}`
}
function reviewPrompt(t, build) {
  return `${COMMON(t.key)}
YOU ARE THE REVIEWER for track ${t.key} (items ${t.items}). BREAK it. Do NOT edit or commit code (captures and scratch scripts under ${SP}/env/${t.key}/ are fine). Read \`git log ${BASE}..HEAD\` and \`git diff ${BASE}..HEAD\` in /home/user/wt/${t.key}.
The builder's account (trust nothing you have not checked):
${JSON.stringify(build, null, 1).slice(0, 16000)}
What to check: ${t.review_focus}
And against the ORIGINAL: run it, screenshot the same things, and report every difference the user's asks (${SP}/user_asks.md) do not cover.
Also: scenarios assert state, not strings; existing scenarios the change breaks were updated; Lua 5.1; hot reload; nil paths; per-frame garbage; the lints (run them).
Run the builder's scenarios by name (only those, plus the lints and the few existing ones the focus names) and take your own captures and LOOK at them. Findings with severity blocker/major/minor/nit, each with where and a concrete repro. "No findings" honestly if none.`
}
function fixPrompt(t, build, review) {
  const worth = review.findings.filter(f => f.severity !== 'nit')
  return `${COMMON(t.key)}
YOU ARE FIXING track ${t.key} (items ${t.items}) after an adversarial review. Read \`git log ${BASE}..HEAD\` and the diff first. If \`git status\` shows uncommitted changes, a fixer before you was cut off by a usage limit: read them, keep what is sound, finish it, and COMMIT EACH FIX AS SOON AS IT WORKS.
The builder's account:
${JSON.stringify(build, null, 1).slice(0, 12000)}
The review's findings (fix every blocker and major; cheap and clearly-right minors; verify each yourself first -- if one is wrong, say why in not_fixed):
${JSON.stringify(worth, null, 1).slice(0, 14000)}
Run only the scenarios you touch or the findings name, plus the lints, by name. Commit. Return the FULL updated progress entry for the track (every item), and dated notes.`
}

phase('Build')
const builds = []
for (let i = 0; i < T.steps.length; i++) {
  const r = await agent(buildPrompt(T, i), { label: `build:${T.key}:${i + 1}`, phase: 'Build', schema: BUILD_SCHEMA })
  if (!r) { log(`build ${T.key} step ${i + 1} returned nothing`); return { track: T.key, failed: true, builds } }
  builds.push(r)
}
const merged = {
  summary: builds.map(x => x.summary).join('\n---\n'),
  files: [...new Set(builds.flatMap(x => x.files))],
  shared_code_touched: builds.flatMap(x => x.shared_code_touched),
  generated_files_changed: builds.flatMap(x => x.generated_files_changed),
  scenarios_added: builds.flatMap(x => x.scenarios_added),
  scenarios_changed: builds.flatMap(x => x.scenarios_changed),
  scenarios_run: builds.map(x => x.scenarios_run).join(' | '),
  captures: builds.flatMap(x => x.captures),
  measurements: builds.flatMap(x => x.measurements),
  original_compared: builds.flatMap(x => x.original_compared),
  choices: builds.flatMap(x => x.choices),
  art_wanted: builds.flatMap(x => x.art_wanted),
  found: builds.flatMap(x => x.found),
  progress_entry: builds.map(x => x.progress_entry).join('\n\n'),
  dated_notes: builds.map(x => x.dated_notes).join('\n'),
}
phase('Review')
const review = await agent(reviewPrompt(T, merged), { label: `review:${T.key}`, phase: 'Review', schema: REVIEW_SCHEMA })
let fix = null
const worth = (review && review.findings || []).filter(f => f.severity !== 'nit')
if (review && worth.length) {
  phase('Fix')
  fix = await agent(fixPrompt(T, merged, review), { label: `fix:${T.key}`, phase: 'Fix', schema: FIX_SCHEMA })
} else log(`${T.key}: review found nothing to fix`)
return { track: T.key, failed: false, build: merged, review, fix }
